### ISSUE TITLE
KeyError: 'is_user_system_message'

### ISSUE THREAD

**Issue by iveskins** [mohamed-chs/chatgpt-history-export-to-md#22]
**Describe the bug**
I was getting a crash part way through the run

`Writing Markdown 📄 files:   3%|██                                                                           | 12/452 [00:00<00:00, 833.60it/s]
Traceback (most recent call last):
  File "/home/me/tools/code/public/chatgpt-history-export-to-md/main.py", line 227, in <module>
    main()
  File "/home/me/tools/code/public/chatgpt-history-export-to-md/main.py", line 103, in main
    conversation.save_to_dir(markdown_folder)
  File "/home/me/tools/code/public/chatgpt-history-export-to-md/models/conversation.py", line 329, in save_to_dir
    file.write(self.markdown)
  File "/home/me/tools/code/public/chatgpt-history-export-to-md/models/conversation.py", line 286, in markdown
    markdown = self.yaml_header
  File "/home/me/tools/code/public/chatgpt-history-export-to-md/models/conversation.py", line 256, in yaml_header
    "custom_instructions": self.custom_instructions,
  File "/home/ivan/tools/code/public/chatgpt-history-export-to-md/models/conversation.py", line 239, in custom_instructions
    if context_message and context_message.metadata["is_user_system_message"]:
KeyError: 'is_user_system_message'
`

**To Reproduce**
I think some of my data is missing a "is_user_system_message" key? 

**Additional context**
i updated 
line 239 in conversation.py to use the get method so it doesnt fail is that key is not there.
        if context_message and context_message.metadata.get("is_user_system_message", None):

**Comment by mohamed-chs** [comment]
Thanks for pointing that out. These data inconsistencies are kinda odd ngl. Get your act together Openai smh ..
I implemented your fix ! Lemme know if you have further issues.
