### ISSUE TITLE
ImportError: cannot import name 'Unpack' from 'typing'

### ISSUE THREAD

**Issue by RaduPrusan** [mohamed-chs/chatgpt-history-export-to-md#25]
**Describe the bug**
python -m convoviz
Traceback (most recent call last):
  File "C:\ProgramData\miniforge3\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\miniforge3\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\miniforge3\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\miniforge3\lib\site-packages\convoviz\__init__.py", line 3, in <module>
    from . import configuration, data_analysis, long_runs, models, utils
  File "C:\ProgramData\miniforge3\lib\site-packages\convoviz\configuration.py", line 18, in <module>
    from .models import Conversation, Message
  File "C:\ProgramData\miniforge3\lib\site-packages\convoviz\models\__init__.py", line 3, in <module>
    from ._conversation import Conversation
  File "C:\ProgramData\miniforge3\lib\site-packages\convoviz\models\_conversation.py", line 11, in <module>
    from typing import TYPE_CHECKING, Any, ClassVar, Unpack
ImportError: cannot import name 'Unpack' from 'typing' (C:\ProgramData\miniforge3\lib\typing.py)

python --version
Python 3.10.12

**Comment by mohamed-chs** [comment]
Thanks for raising the issue !
Yep that's `Unpack`, use to be in the `typing_extensions` module, now in `typing` as of Python 3.12.
I'll fix that to work for previous versions.
