### ISSUE TITLE
, you're encountering a validation error related to the handling of image data in your conversation history.

### ISSUE THREAD

**Issue by Kmfernan5** [mohamed-chs/chatgpt-history-export-to-md#35]
**Describe the bug**

➡️ https://github.com/mohamed-chs/chatgpt-history-export-to-md/issues/new/choose 🔗

? Enter the path to the zip file : C:\Users\mydjt\Downloads\2024_03_20_chatgpt_export_cd833544d1e9d430427877b3357ec5b40
df5d0062769dde85ac4b09bc0e74a93-2024-03-20-19-53-00.zip
? Enter the path to the output folder : C:\Users\mydjt\Documents\ChatGPT Data
? Enter the message header (#) for messages from 'system' : ### System
? Enter the message header (#) for messages from 'user' : # User
? Enter the message header (#) for messages from 'assistant' : # ChatGPT
? Enter the message header (#) for messages from 'tool' : ### Tool output
? Select the LaTeX math delimiters you want to use : default
? Select the YAML metadata headers you want to include : done (9 selections)
? Select the font you want to use for the word clouds : RobotoSlab-Thin
? Select the color theme you want to use for the word clouds : prism
? Enter custom stopwords (separated by commas) : use, file,

And we're off! 🚀🚀🚀

Loading data 📂 ...

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mydjt\Documents\GitHub\chatgpt-history-export-to-md2\convoviz\__main__.py", line 5, in <module>
    main()
  File "C:\Users\mydjt\Documents\GitHub\chatgpt-history-export-to-md2\convoviz\cli.py", line 38, in main
    entire_collection = ConversationSet.from_zip(user.configs["zip_filepath"])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mydjt\Documents\GitHub\chatgpt-history-export-to-md2\convoviz\models\_conversation_set.py", line 55, in from_zip
    return cls.from_json(convos_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mydjt\Documents\GitHub\chatgpt-history-export-to-md2\convoviz\models\_conversation_set.py", line 47, in from_json
    return cls(array=loads(file.read()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mydjt\Documents\GitHub\chatgpt-history-export-to-md2\env\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 182 validation errors for ConversationSet
array.59.mapping.bbb217b1-2cd2-4c3e-a26c-0cf7dbe287e0.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.59.mapping.bbb21ce6-538c-46a9-b944-19711e2a3611.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]

    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.4333.mapping.5bc365ac-6368-491f-9ad2-3bdd43b40ae8.message.content.parts.3
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type

**To Reproduce**
1.Follow directions. See above. 

**Expected behavior**
Normal output

**Screenshots**

https://share.zight.com/RBukD70Y
https://share.zight.com/ApuPdnyD

**OS**
 - OS: Windows 11

**Additional context**

I copied and pasted everything into chatgpt and got this as a reply. Any way to fix this? 

It seems like you're trying to use the ChatGPT Data Visualizer (Convoviz) to visualize your ChatGPT conversation data. However, you're encountering a validation error related to the handling of image data in your conversation history. The error suggests that the tool is expecting a string input, but it's receiving a dictionary containing image data instead.

This might be due to a limitation in the current version of Convoviz, which may not fully support conversations that include image data. You might want to check if there are updates to Convoviz that address this issue, or you could try removing the image data from your conversation history before running the tool.

**Comment by mmatiaschek** [comment]
Same problem, not able to generate any output on MacOS Sonoma 14.2.1 with Python 3.11.5

```
(base) [~/Downloads]$ python3 -m convoviz
Welcome to ChatGPT Data Visualizer ✨📊!

Follow the instructions in the command line.

Press 'ENTER' to select the default options.

If you encounter any issues 🐛, please report 🚨 them here:

➡️ https://github.com/mohamed-chs/chatgpt-history-export-to-md/issues/new/choose 🔗


? Enter the path to the zip file : /Users/mmatiaschek/Downloads/9c718117734d01476f35166ed9676d2436f333b133df31c94e60b749183ca7dc-2024-03-29-10-14-24.zip
? Enter the path to the output folder : /Users/mmatiaschek/Documents/ChatGPT Data
? Enter the message header (#) for messages from 'system' : ### System
? Enter the message header (#) for messages from 'user' : # Me
? Enter the message header (#) for messages from 'assistant' : # ChatGPT
? Enter the message header (#) for messages from 'tool' : ### Tool output
? Select the LaTeX math delimiters you want to use : default
? Select the YAML metadata headers you want to include : done (9 selections)
? Select the font you want to use for the word clouds : RobotoSlab-Thin
? Select the color theme you want to use for the word clouds : prism
? Enter custom stopwords (separated by commas) : use, file,


And we're off! 🚀🚀🚀

Loading data 📂 ...

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/convoviz/__main__.py", line 5, in <module>
    main()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/convoviz/cli.py", line 38, in main
    entire_collection = ConversationSet.from_zip(user.configs["zip_filepath"])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/convoviz/models/_conversation_set.py", line 55, in from_zip
    return cls.from_json(convos_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/convoviz/models/_conversation_set.py", line 47, in from_json
    return cls(array=loads(file.read()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 32 validation errors for ConversationSet
array.8.mapping.aaa237d2-0408-462c-8e12-418b9e140cf5.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.9.mapping.5cd5a2aa-094c-4705-ba4c-0c8a95c8c13f.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.10.mapping.c392ff96-e8bf-4714-bbd3-bb6f6a9f5e17.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.11.mapping.aaa20c5e-3ccb-493a-a080-7d81dafe5e6c.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.11.mapping.aaa20c5e-3ccb-493a-a080-7d81dafe5e6c.message.content.parts.1
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.40.mapping.aaa2dec0-1fa6-46a8-8d65-d4025185c8ca.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.40.mapping.aaa24123-29bc-4392-8f20-1f0036f1394d.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.45.mapping.aaa27805-6257-467b-b749-9a11c3e6ad0a.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.45.mapping.aaa27805-6257-467b-b749-9a11c3e6ad0a.message.content.parts.1
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.47.mapping.bbb26337-3d71-4a69-b1f1-71f9c9d5d2cc.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.52.mapping.26bc882a-fd83-459f-bb68-6b22d70bb7a9.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.52.mapping.5fcd4ef0-31db-4955-86bf-791c43d9623c.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.52.mapping.72dabd12-cad0-479c-9624-f75c51a34e51.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.57.mapping.89d97fec-ec5f-493a-813e-3e48c0edee02.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.57.mapping.90587f7e-921f-48d4-a822-f128dfb77f80.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.70.mapping.aaa2d054-cc22-471f-a2af-2b9a6ae0a277.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.73.mapping.aaa22d2e-c9cc-4bdd-b1fb-b0d4593098fb.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.73.mapping.81749cbe-8a81-4af1-b1d9-e6539a7d9b45.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.73.mapping.aaa230e8-60bf-4e93-8aff-2037e7ad6b85.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.73.mapping.11fc50f5-658b-462d-b962-d58265b5c053.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.73.mapping.0ab14798-27a8-45d4-b072-4e12db4bc53d.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.73.mapping.29b84005-9a04-4cda-8079-3308179963f3.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.73.mapping.4ac17b5b-48d9-4812-bb24-3360384da56c.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.74.mapping.552d10c4-9669-41c9-ae87-75666fea0c62.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.84.mapping.bbb235c9-6841-4107-bd3f-59c959a51dd5.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.84.mapping.bbb235c9-6841-4107-bd3f-59c959a51dd5.message.content.parts.1
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.84.mapping.bbb235c9-6841-4107-bd3f-59c959a51dd5.message.content.parts.2
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.84.mapping.bbb235c9-6841-4107-bd3f-59c959a51dd5.message.content.parts.3
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... None, 'metadata': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.93.mapping.48737a78-9c62-4320-8b32-cb57c29e07a3.message.content.parts.0
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.93.mapping.48737a78-9c62-4320-8b32-cb57c29e07a3.message.content.parts.1
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.93.mapping.48737a78-9c62-4320-8b32-cb57c29e07a3.message.content.parts.2
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
array.93.mapping.48737a78-9c62-4320-8b32-cb57c29e07a3.message.content.parts.3
  Input should be a valid string [type=string_type, input_value={'content_type': 'image_a... generation metadata'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
```
